config/routes.php
<?php
/**
 * Routes configuration.
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * It's loaded within the context of `Application::routes()` method which
 * receives a `RouteBuilder` instance `$routes` as method argument.
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

 use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\Route\DashedRoute;
use Cake\Routing\RouteBuilder;

/*
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 */
/** @var \Cake\Routing\RouteBuilder $routes */
$routes->setRouteClass(DashedRoute::class);

$routes->scope('/', function (RouteBuilder $builder) {
    $builder->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httponly' => true,
    ]));
    // $builder->applyMiddleware('csrf');
    /*
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, templates/Pages/home.php)...
     */
    //$builder->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $builder->connect('/', ['controller' => 'Pokemons', 'action' => 'index','statistique']);
    /*
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $builder->connect('/pages/*', 'Pages::display');

    /*
     * Connect catchall routes for all controllers.
     *
     * The `fallbacks` method is a shortcut for
     *
     * ```
     * $builder->connect('/:controller', ['action' => 'index']);
     * $builder->connect('/:controller/:action/*', []);
     * ```
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $builder->fallbacks();
});

/*
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * $routes->scope('/api', function (RouteBuilder $builder) {
 *     // No $builder->applyMiddleware() here.
 *     
 *     // Parse specified extensions from URLs
 *     // $builder->setExtensions(['json', 'xml']);
 *     
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Pokemon.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Pokemon Entity
 *
 * @property int $id
 * @property string $name
 * @property int $height
 * @property int $weight
 * @property string $default_front_sprite_url
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\PokemonStat[] $pokemon_stats
 * @property \App\Model\Entity\PokemonType[] $pokemon_types
 */
class Pokemon extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];


    /**
     * Undocumented function
     *
     * @return string
     */
    protected function _getMainSprite()
    {
        return $this->default_front_sprite_url ? $this->default_front_sprite_url : 'unknown.png';
    }

    /**
     * Return the first type for a pokemon
     *
     * @return string
     */
    protected function _getFirstType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)
                ->extract('type.name')
                ->first();
        }

        return 'normal';
    }

    /**
     * Return the first type for a pokemon
     *
     * @return string
     */
    protected function _getSecondType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)
                ->extract('type.name')
                ->skip(1)
                ->first();
        }

        return 'normal';
    }

    protected function _getHasSecondType()
    {
        if (isset($this->pokemon_types) && !empty($this->pokemon_types)) {
            return collection($this->pokemon_types)->count() > 1;
        }

        return false;
    }

    /**
     * Return the first stat for a pokemon
     *
     * @return string
     */
    protected function _getFirstStat()
    {
        if (isset($this->pokemon_stats) && !empty($this->pokemon_stats)) {
            return collection($this->pokemon_stats)
                ->extract('value')
                ->first();
        }

        return 'normal';
    }

    /**
     * Return the first stat for a pokemon
     *
     * @return string
     */
    protected function _getSecondStat()
    {
        if (isset($this->pokemon_stats) && !empty($this->pokemon_stats)) {
            return collection($this->pokemon_stats)
                ->extract('value')
                ->skip(1)
                ->first();
        }

        return 'normal';
    }

    /**
     * Return the first stat for a pokemon
     *
     * @return string
     */
    protected function _getThirdStat()
    {
        if (isset($this->pokemon_stats) && !empty($this->pokemon_stats)) {
            return collection($this->pokemon_stats)
                ->extract('value')
                ->skip(2)
                ->first();
        }

    }

    /**
     * Return the first stat for a pokemon
     *
     * @return string
     */
    protected function _getFourStat()
    {
        if (isset($this->pokemon_stats) && !empty($this->pokemon_stats)) {
            return collection($this->pokemon_stats)
                ->extract('value')
                ->skip(3)
                ->first();
        }

    }

    /**
     * Return the first stat for a pokemon
     *
     * @return string
     */
    protected function _getFiveStat()
    {
        if (isset($this->pokemon_stats) && !empty($this->pokemon_stats)) {
            return collection($this->pokemon_stats)
                ->extract('value')
                ->skip(4)
                ->first();
        }

    }
    /**
     * Return the first stat for a pokemon
     *
     * @return string
     */
    protected function _getSixStat()
    {
        if (isset($this->pokemon_stats) && !empty($this->pokemon_stats)) {
            return collection($this->pokemon_stats)
                ->extract('value')
                ->skip(5)
                ->first();
        }

    }
}

src/Model/Entity/PokemonType.php
<?php
declare(strict_types=1);

namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * PokemonType Entity
 *
 * @property int $id
 * @property string $pokemon_id
 * @property string $type_id
 * @property \Cake\I18n\FrozenTime $created
 * @property \Cake\I18n\FrozenTime $modified
 *
 * @property \App\Model\Entity\Pokemon $pokemon
 * @property \App\Model\Entity\Type $type
 */
class PokemonType extends Entity
{
    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
}

src/Model/Table/PokemonsTable.php
<?php
declare(strict_types=1);

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Pokemons Model
 *
 * @property \App\Model\Table\PokemonStatsTable&\Cake\ORM\Association\HasMany $PokemonStats
 * @property \App\Model\Table\PokemonTypesTable&\Cake\ORM\Association\HasMany $PokemonTypes
 *
 * @method \App\Model\Entity\Pokemon newEmptyEntity()
 * @method \App\Model\Entity\Pokemon newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon get($primaryKey, $options = [])
 * @method \App\Model\Entity\Pokemon findOrCreate($search, ?callable $callback = null, $options = [])
 * @method \App\Model\Entity\Pokemon patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Pokemon|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Pokemon saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface|false deleteMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface deleteManyOrFail(iterable $entities, $options = [])
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PokemonsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config): void
    {
        parent::initialize($config);

        $this->setTable('pokemons');
        $this->setDisplayField('name');
        $this->setPrimaryKey('id');

        $this->addBehavior('Timestamp');

        $this->hasMany('PokemonStats', [
            'foreignKey' => 'pokemon_id',
            'saveStrategy' => 'replace',
        ]);
        $this->hasMany('PokemonTypes', [
            'foreignKey' => 'pokemon_id',
            'saveStrategy' => 'replace',
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator): Validator
    {
        $validator
            ->integer('id')
            ->allowEmptyString('id', null, 'create');

        $validator
            ->scalar('name')
            ->maxLength('name', 255)
            ->requirePresence('name', 'create')
            ->notEmptyString('name');

        $validator
            ->integer('height')
            ->requirePresence('height', 'create')
            ->notEmptyString('height');

        $validator
            ->integer('weight')
            ->requirePresence('weight', 'create')
            ->notEmptyString('weight');

        $validator
            ->scalar('default_front_sprite_url')
            ->maxLength('default_front_sprite_url', 255)
            ->requirePresence('default_front_sprite_url', 'create')
            ->notEmptyString('default_front_sprite_url');

        $validator
            ->scalar('default_back_sprite_url')
            ->maxLength('default_back_sprite_url', 255)
            ->requirePresence('default_back_sprite_url', 'create')
            ->notEmptyString('default_back_sprite_url');

        $validator
            ->scalar('Shiny_front_sprite_url')
            ->maxLength('Shiny_front_sprite_url', 255)
            ->requirePresence('Shiny_front_sprite_url', 'create')
            ->notEmptyString('Shiny_front_sprite_url');

        $validator
            ->scalar('Shiny_back_sprite_url')
            ->maxLength('Shiny_back_sprite_url', 255)
            ->requirePresence('Shiny_back_sprite_url', 'create')
            ->notEmptyString('Shiny_back_sprite_url');

        return $validator;
    }

    /**
     * Format Data for save
     *
     * @param array $pokeApiData Data from Poke Api
     * @return array
     */
    public function formatDataForSave($pokeApiData)
    {
        $pokemonStats = $this->PokemonStats->formatDataForSave($pokeApiData['stats']);
        $pokemonTypes = $this->PokemonTypes->formatDataForSave($pokeApiData['types']);

        return [
            'pokedex_number' => $pokeApiData['id'],
            'name' => $pokeApiData['name'],
            'default_front_sprite_url' => $pokeApiData['sprites']['front_default'],
            'default_back_sprite_url' => $pokeApiData['sprites']['back_default'],
            'Shiny_front_sprite_url' => $pokeApiData['sprites']['front_shiny'],
            'Shiny_back_sprite_url' => $pokeApiData['sprites']['back_shiny'],
            'height' => $pokeApiData['height'],
            'weight' => $pokeApiData['weight'],
            'pokemon_stats' => $pokemonStats,
            'pokemon_types' => $pokemonTypes,
        ];
    }

    public function FAIRY()
    {
        $query = $this->query()
        ->select(['fee'=>$this->query()->func()->count('pokedex_number')])
        ->innerJoin('pokemon_types',['pokemon_types.pokemon_id = pokedex_number'])
        ->where([ $this->query()->newExpr()->eq('type_id',10),
           'OR' => [[$this->query()->newExpr()->between('pokedex_number',1,151)], [$this->query()->newExpr()->between('pokedex_number',252,386)], [$this->query()->newExpr()->between('pokedex_number',722,809)]],
        ]);

        return $query->all()->toArray()[0];
    }

    public function POIDS()
    {
        $query = $this->query()
        ->select(['poids'=>$this->query()->func()->avg('weight')])
        ->where([
            $this->query()->newExpr()->between('pokedex_number',387,493)
        ]);
        return $query->all()->toArray()[0];
        
    }

    public function STATS():array
    {
        $query = $this->query()
        ->select(["name","value"=>"pokemon_stats.value"])
        ->innerJoin('pokemon_stats',['pokemon_stats.pokemon_id = pokedex_number'])
        ->where([
            $this->query()->newExpr()->eq('stat_id',6)
        ])
        ->orderDesc('value')
        ->limit(10);
        return $query->all()->toArray();
        
    }
}

src/Controller/PokemonsController.php
<?php
declare(strict_types=1);

namespace App\Controller;

/**
 * Pokemons Controller
 *
 * @property \App\Model\Table\PokemonsTable $Pokemons
 * @method \App\Model\Entity\Pokemon[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class PokemonsController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */
    public function index()
    {
        $this->paginate = [
            'limit' => 30,
        ];

        $pokemons = $this->Pokemons->find('all')->contain(['PokemonStats.Stats', 'PokemonTypes.Types']);
        $pokemons = $this->paginate($pokemons);

        $this->set(compact('pokemons'));
    }

    /**
     * View method
     *
     * @param string|null $id Pokemon id.
     * @return \Cake\Http\Response|null|void Renders view
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $pokemon = $this->Pokemons->get($id, [
            'contain' => ['PokemonStats.Stats', 'PokemonTypes.Types'],
        ]);

        $this->set(compact('pokemon'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Pokemon id.
     * @return \Cake\Http\Response|null|void Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $pokemon = $this->Pokemons->get($id);
        if ($this->Pokemons->delete($pokemon)) {
            $this->Flash->success(__('The pokemon has been deleted.'));
        } else {
            $this->Flash->error(__('The pokemon could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function statistique(){
        return $this->render('/Pokemons/statistique');
    }

}

templates/Pokemons/index.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon[]|\Cake\Collection\CollectionInterface $pokemons
 */
?>
<div class="pokemons index content">
    <h3><?= __('Pokemons') ?></h3>
    <div class="row">
        <?php foreach ($pokemons as $pokemon) : ?>
                <div class="col-12 col-md-4 col-sm-6 col-xs-12">
                    <?= $this->element('Pokemons/card', ['pokemon' => $pokemon]); ?>
                </div>
        <?php endforeach; ?>
    </div>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(__('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')) ?></p>
    </div>
</div>

templates/Pokemons/statistique.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon $pokemon
 * @var \App\Model\Entity\Stat $stat
 * @var \App\Model\Entity\PokemonStat $pokemonstat
 * @var \App\Model\Table\PokemonsTable $poketable
 * 
 */
use \App\Model\Table\PokemonsTable;

 $poketable = new PokemonsTable();
 $index = 1;
?>
<table>
<h3>Nombre de Pokémon de type fée (1,3,7 Gen): </h3>
<tr>
    
    <td> <?= $poketable->FAIRY()->fee?>  </td>
</tr>
</table>
<br>

<h3>Moyenne du poids des Pokémons de 4Gen : </h3>
<table>
<tr>
    
    <td><?= ($poketable->POIDS()->poids)/10 ?> kg</td>
</tr>
</table>
<br>


<h3>10 Premier Pokémon avec la Vitesse la plus haute : </h3>
<table>
<tr>
<th>Position</th>
<th>Pokémon</th>
<th>Vitesse</th>
</tr>

    <?php foreach($poketable->STATS() as $value):?>
<tr>    
<td>
<?= $index++ ?>. 
</td>
<td>
<?= $value->name?>
</td>
<td>
<?= $value->value?>
</td>
</tr>
    <?php endforeach ?>


</table>

templates/Pokemons/view.php
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Pokemon $pokemon
 * @var \App\Model\Entity\Stat $stat
 * @var \App\Model\Entity\PokemonStat $pokemonstat
 */
?>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
    <header>
        <div class="pokemons view content">
            <h1><?= h($pokemon->name) ?></h1>
                <figcaption class="card__caption">
                    <h3 class="card__type <?= $pokemon->first_type ?>">
                        <?= $pokemon->first_type ?>
                    </h3>
                    <h3 class="card__second_type <?= $pokemon->second_type ?>">
                        <?= $pokemon->second_type ?>
                    </h3>
        </div>
    </header>
    <main>
        <div class="rows">
            <div class="column" style="background-color:#aaa;">
                <?= $this->Html->image($pokemon->main_sprite); ?>
            </div>
            <div class="column" style="background-color:#bbb;">
                <div class="pokemons view content">
                    <table class="card__stats">
                        <tbody>
                            <tr>
                                <th>hp</th>
                                <td><?= $pokemon->first_stat?></td>
                            </tr>
                            <tr>
                                <th>Defense</th>
                                <td><?= $pokemon->third_stat?></td>
                            </tr>
                            <tr>
                                <th>Attack</th>
                                <td><?= $pokemon->second_stat?></td>
                            </tr>
                            <tr>
                                <th>Special Attack</th>
                                <td><?= $pokemon->four_stat ?></td>
                            </tr>
                            <tr>
                                <th>Special Defense</th>
                                <td><?= $pokemon->five_stat ?></td>
                            </tr>
                            <tr>
                                <th>Speed</th>
                                <td><?= $pokemon->six_stat ?></td>
                            </tr>
                        </tbody>
                    </table>  
                </div>
            </div>
        </div>
</main>
    <footer>
        <div class="pokemons view content">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <div class="card__image-container poke-sprite-<?= $pokemon->pokedex_number ?>" id="main-poke-sprites">
                            <?= $this->Html->image($pokemon->main_sprite); ?>
                        </div>
                    </div>

                    <div class="item">
                        <div class="card__image-container poke-sprite-<?= $pokemon->pokedex_number ?>" id="main-poke-sprites">
                            <?php if (!$pokemon->default_back_sprite_url) : ?>
                                <?= $this->Html->image($pokemon->main_sprite); ?>
                            <?php endif ?>
                            <?php if ($pokemon->default_back_sprite_url) : ?>
                                <?= $this->Html->image($pokemon->default_back_sprite_url); ?>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="item">
                        <div class="card__image-container poke-sprite-<?= $pokemon->pokedex_number ?>" id="main-poke-sprites">
                            <?php if (!$pokemon->Shiny_front_sprite_url) : ?>
                                <?= $this->Html->image($pokemon->main_sprite); ?>
                            <?php endif ?>
                            <?php if ($pokemon->Shiny_front_sprite_url) : ?>
                                <?= $this->Html->image($pokemon->Shiny_front_sprite_url); ?>
                            <?php endif ?>
                        </div>
                    </div>

                    <div class="item">
                        <div class="card__image-container poke-sprite-<?= $pokemon->pokedex_number ?>" id="main-poke-sprites">
                            <?php if (!$pokemon->Shiny_back_sprite_url) : ?>
                                <?= $this->Html->image($pokemon->main_sprite); ?>
                            <?php endif ?>
                            <?php if ($pokemon->Shiny_back_sprite_url) : ?>
                                <?= $this->Html->image($pokemon->Shiny_back_sprite_url); ?>
                            <?php endif ?>
                        </div>
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </footer>
</body>